#define MAX_CAMERAS 8
#define MAX_LIGHTS 16

#define INVALID_INDEX 0xFFFFFFFF

#define WORLD_SIZE  10000.0

#define RAY_FLAGS_HIT           0x00000001
#define RAY_FLAGS_IS_EMITTER    0x00000002
#define RAY_FLAGS_SPECULAR      0x00000004
#define RAY_FLAGS_REFLECTION    0x00000008
#define RAY_FLAGS_TRANSMISSION  0x00000010

#define LIGHT_TYPE_POINT        0
#define LIGHT_TYPE_DIRECTIONAL  1
#define LIGHT_TYPE_SPOT         2
#define LIGHT_TYPE_QUAD         3
#define LIGHT_TYPE_SPHERE       4

#define ENV_TYPE_SKY    0
#define ENV_TYPE_MAP    1

#define CALLABLE_GEN_CAMERA_RAY_BEGIN           0
#define CALLABLE_GEN_PERSPECTIVE_CAMERA_RAY     0
#define CALLABLE_GEN_ORTHOGRAPHIC_CAMERA_RAY    1

#define CALLABLE_ENV_BEGIN              2
#define CALLABLE_ENV_SKY_EVAL           2
#define CALLABLE_ENV_SKY_SAMPLE         3
#define CALLABLE_ENV_MAP_EVAL           4
#define CALLABLE_ENV_MAP_SAMPLE         5

#define CALLABLE_LIGHT_BEGIN            6
#define CALLABLE_LIGHT_POINT            6
#define CALLABLE_LIGHT_DIRECTIONAL      7
#define CALLABLE_LIGHT_SPOT             8
#define CALLABLE_LIGHT_QUAD             9
#define CALLABLE_LIGHT_SPHERE           10
#define CALLABLE_MATERIAL_BXDF_BEGIN    11

#define MEDIUM_NONE     0
#define MEDIUM_ABSORB   1
#define MEDIUM_SCATTER  2
#define MEDIUM_EMISSIVE 3
